# Generated by Django 5.1.4 on 2025-01-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
