# Generated by Django 5.1.4 on 2025-01-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santas_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='santa_list',
        ),
        migrations.AddField(
            model_name='kid',
            name='santas_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='santas_list.santas_list'),
        ),
    ]
