# Generated by Django 5.1.4 on 2025-01-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santas_list', '0002_remove_kid_santa_list_kid_santas_list'),
        ('toy_factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='coal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kid_coal', to='toy_factory.coal'),
        ),
        migrations.AddField(
            model_name='kid',
            name='toy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kid_toy', to='toy_factory.toy'),
        ),
        migrations.AddField(
            model_name='kid',
            name='wanted_toy',
            field=models.CharField(default='car', max_length=50),
            preserve_default=False,
        ),
    ]
